[libraries]
google-authClient = { module = "com.google.oauth-client:google-oauth-client-jetty", version = "1.34.1" }
google-apis-sheets = { module = "com.google.apis:google-api-services-sheets", version = "v4-rev20230815-2.0.0" }
google-apis-drive = { module = "com.google.apis:google-api-services-drive", version = "v3-rev20231120-2.0.0" }
google-auth-oauth2 = { module = "com.google.auth:google-auth-library-oauth2-http", version = "1.19.0" }