package ru.raysmith.google.drive

import com.google.api.services.drive.model.*

fun about(setup: About.() -> Unit) = About().apply(setup)
fun app(setup: App.() -> Unit) = App().apply(setup)
fun appIcons(setup: AppIcons.() -> Unit) = AppIcons().apply(setup)
fun appList(setup: AppList.() -> Unit) = AppList().apply(setup)
fun change(setup: Change.() -> Unit) = Change().apply(setup)
fun changeList(setup: ChangeList.() -> Unit) = ChangeList().apply(setup)
fun channel(setup: Channel.() -> Unit) = Channel().apply(setup)
fun comment(setup: Comment.() -> Unit) = Comment().apply(setup)
fun commentList(setup: CommentList.() -> Unit) = CommentList().apply(setup)
fun contentRestriction(setup: ContentRestriction.() -> Unit) = ContentRestriction().apply(setup)
fun drive(setup: Drive.() -> Unit) = Drive().apply(setup)
fun driveList(setup: DriveList.() -> Unit) = DriveList().apply(setup)
fun file(setup: File.() -> Unit) = File().apply(setup)
fun fileList(setup: FileList.() -> Unit) = FileList().apply(setup)
fun generatedIds(setup: GeneratedIds.() -> Unit) = GeneratedIds().apply(setup)
fun label(setup: Label.() -> Unit) = Label().apply(setup)
fun labelField(setup: LabelField.() -> Unit) = LabelField().apply(setup)
fun labelFieldModification(setup: LabelFieldModification.() -> Unit) = LabelFieldModification().apply(setup)
fun labelList(setup: LabelList.() -> Unit) = LabelList().apply(setup)
fun labelModification(setup: LabelModification.() -> Unit) = LabelModification().apply(setup)
fun modifyLabelsRequest(setup: ModifyLabelsRequest.() -> Unit) = ModifyLabelsRequest().apply(setup)
fun modifyLabelsResponse(setup: ModifyLabelsResponse.() -> Unit) = ModifyLabelsResponse().apply(setup)
fun permission(setup: Permission.() -> Unit) = Permission().apply(setup)
fun permissionList(setup: PermissionList.() -> Unit) = PermissionList().apply(setup)
fun reply(setup: Reply.() -> Unit) = Reply().apply(setup)
fun replyList(setup: ReplyList.() -> Unit) = ReplyList().apply(setup)
fun revision(setup: Revision.() -> Unit) = Revision().apply(setup)
fun revisionList(setup: RevisionList.() -> Unit) = RevisionList().apply(setup)
fun startPageToken(setup: StartPageToken.() -> Unit) = StartPageToken().apply(setup)
fun teamDrive(setup: TeamDrive.() -> Unit) = TeamDrive().apply(setup)
fun teamDriveList(setup: TeamDriveList.() -> Unit) = TeamDriveList().apply(setup)
fun user(setup: User.() -> Unit) = User().apply(setup)