@file:Suppress("unused")

package ru.raysmith.google.gmail.utils

import com.google.api.services.gmail.model.*

fun autoForwarding(setup: AutoForwarding.() -> Unit) = AutoForwarding().apply(setup)
fun batchDeleteMessagesRequest(setup: BatchDeleteMessagesRequest.() -> Unit) = BatchDeleteMessagesRequest().apply(setup)
fun batchModifyMessagesRequest(setup: BatchModifyMessagesRequest.() -> Unit) = BatchModifyMessagesRequest().apply(setup)
fun cseIdentity(setup: CseIdentity.() -> Unit) = CseIdentity().apply(setup)
fun cseKeyPair(setup: CseKeyPair.() -> Unit) = CseKeyPair().apply(setup)
fun csePrivateKeyMetadata(setup: CsePrivateKeyMetadata.() -> Unit) = CsePrivateKeyMetadata().apply(setup)
fun delegate(setup: Delegate.() -> Unit) = Delegate().apply(setup)
fun disableCseKeyPairRequest(setup: DisableCseKeyPairRequest.() -> Unit) = DisableCseKeyPairRequest().apply(setup)
fun draft(setup: Draft.() -> Unit) = Draft().apply(setup)
fun enableCseKeyPairRequest(setup: EnableCseKeyPairRequest.() -> Unit) = EnableCseKeyPairRequest().apply(setup)
fun filter(setup: Filter.() -> Unit) = Filter().apply(setup)
fun filterAction(setup: FilterAction.() -> Unit) = FilterAction().apply(setup)
fun filterCriteria(setup: FilterCriteria.() -> Unit) = FilterCriteria().apply(setup)
fun forwardingAddress(setup: ForwardingAddress.() -> Unit) = ForwardingAddress().apply(setup)
fun hardwareKeyMetadata(setup: HardwareKeyMetadata.() -> Unit) = HardwareKeyMetadata().apply(setup)
fun history(setup: History.() -> Unit) = History().apply(setup)
fun historyLabelAdded(setup: HistoryLabelAdded.() -> Unit) = HistoryLabelAdded().apply(setup)
fun historyLabelRemoved(setup: HistoryLabelRemoved.() -> Unit) = HistoryLabelRemoved().apply(setup)
fun historyMessageAdded(setup: HistoryMessageAdded.() -> Unit) = HistoryMessageAdded().apply(setup)
fun historyMessageDeleted(setup: HistoryMessageDeleted.() -> Unit) = HistoryMessageDeleted().apply(setup)
fun imapSettings(setup: ImapSettings.() -> Unit) = ImapSettings().apply(setup)
fun kaclsKeyMetadata(setup: KaclsKeyMetadata.() -> Unit) = KaclsKeyMetadata().apply(setup)
fun label(setup: Label.() -> Unit) = Label().apply(setup)
fun labelColor(setup: LabelColor.() -> Unit) = LabelColor().apply(setup)
fun languageSettings(setup: LanguageSettings.() -> Unit) = LanguageSettings().apply(setup)
fun listCseIdentitiesResponse(setup: ListCseIdentitiesResponse.() -> Unit) = ListCseIdentitiesResponse().apply(setup)
fun listCseKeyPairsResponse(setup: ListCseKeyPairsResponse.() -> Unit) = ListCseKeyPairsResponse().apply(setup)
fun listDelegatesResponse(setup: ListDelegatesResponse.() -> Unit) = ListDelegatesResponse().apply(setup)
fun listDraftsResponse(setup: ListDraftsResponse.() -> Unit) = ListDraftsResponse().apply(setup)
fun listFiltersResponse(setup: ListFiltersResponse.() -> Unit) = ListFiltersResponse().apply(setup)
fun listForwardingAddressesResponse(setup: ListForwardingAddressesResponse.() -> Unit) = ListForwardingAddressesResponse().apply(setup)
fun listHistoryResponse(setup: ListHistoryResponse.() -> Unit) = ListHistoryResponse().apply(setup)
fun listLabelsResponse(setup: ListLabelsResponse.() -> Unit) = ListLabelsResponse().apply(setup)
fun listMessagesResponse(setup: ListMessagesResponse.() -> Unit) = ListMessagesResponse().apply(setup)
fun listSendAsResponse(setup: ListSendAsResponse.() -> Unit) = ListSendAsResponse().apply(setup)
fun listSmimeInfoResponse(setup: ListSmimeInfoResponse.() -> Unit) = ListSmimeInfoResponse().apply(setup)
fun listThreadsResponse(setup: ListThreadsResponse.() -> Unit) = ListThreadsResponse().apply(setup)
fun message(setup: Message.() -> Unit) = Message().apply(setup)
fun messagePart(setup: MessagePart.() -> Unit) = MessagePart().apply(setup)
fun messagePartBody(setup: MessagePartBody.() -> Unit) = MessagePartBody().apply(setup)
fun messagePartHeader(setup: MessagePartHeader.() -> Unit) = MessagePartHeader().apply(setup)
fun modifyMessageRequest(setup: ModifyMessageRequest.() -> Unit) = ModifyMessageRequest().apply(setup)
fun modifyThreadRequest(setup: ModifyThreadRequest.() -> Unit) = ModifyThreadRequest().apply(setup)
fun obliterateCseKeyPairRequest(setup: ObliterateCseKeyPairRequest.() -> Unit) = ObliterateCseKeyPairRequest().apply(setup)
fun popSettings(setup: PopSettings.() -> Unit) = PopSettings().apply(setup)
fun profile(setup: Profile.() -> Unit) = Profile().apply(setup)
fun sendAs(setup: SendAs.() -> Unit) = SendAs().apply(setup)
fun signAndEncryptKeyPairs(setup: SignAndEncryptKeyPairs.() -> Unit) = SignAndEncryptKeyPairs().apply(setup)
fun smimeInfo(setup: SmimeInfo.() -> Unit) = SmimeInfo().apply(setup)
fun smtpMsa(setup: SmtpMsa.() -> Unit) = SmtpMsa().apply(setup)
fun thread(setup: Thread.() -> Unit) = Thread().apply(setup)
fun vacationSettings(setup: VacationSettings.() -> Unit) = VacationSettings().apply(setup)
fun watchRequest(setup: WatchRequest.() -> Unit) = WatchRequest().apply(setup)
fun watchResponse(setup: WatchResponse.() -> Unit) = WatchResponse().apply(setup)
